name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ensure you're using a compatible Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx

      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html docs/ docs/_build/html
          touch docs/_build/html/.nojekyll  # Ensure .nojekyll file is present

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: docs/_build/html
          api_location: ""
