name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Sphinx Docs
    permissions:
       id-token: write
       contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the appropriate Python version

      - name: Install Sphinx and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme  # Install Sphinx and theme

      - name: Ensure conf.py exists in the correct location
        run: |
          if [ ! -f docs/conf.py ]; then
            echo "conf.py not found! Creating a basic conf.py..."
            sphinx-quickstart docs --sep --quiet --project "PyPontem Documentation" --author "Pontem Analytics" --release "1.0" --ext-autodoc --ext-viewcode --no-batchfile
            mv docs/source/* docs/  # Move files from source/ to docs/
            rm -rf docs/source/  # Remove the now empty source directory
          fi

      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html docs/ docs/_build/html
          touch docs/_build/html/.nojekyll  # Prevent GitHub from ignoring _static files

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "docs/_build/html"  # This is where the built documentation is
          api_location: ""  # No API needed
          output_location: "docs/_build/html"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
